package com.language_practice_server.server_demo.auth_service.db.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import java.time.Instant;

/*
    An Entity to store refresh tokens generated by the application or Provider(e.g. Google)
 */
@Entity(name = "refresh_tokens")
public class RefreshTokenEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "user_id", nullable = false)
    private Long userId;
    @Column(name = "token_hash")
    private String refreshTokenHash;
    @Column(name = "issued_at", nullable = false)
    private  Instant issuedAt;
    @Column(name = "expires_at", nullable = false)
    private Instant expiresAt;
    @Column(name = "provider")
    private String provider;
    @Column(name = "provider_token_hash")
    private String providerRefreshTokenHash;
    @Column(name = "revoked", nullable = false)
    private boolean revoked = false;

    public RefreshTokenEntity() {
    }

    public RefreshTokenEntity(Long userId,
                              String refreshTokenHash,
                              Instant issuedAt,
                              Instant expiresAt,
                              String provider,
                              String providerRefreshTokenHash,
                              boolean revoked) {
        this.userId = userId;
        this.refreshTokenHash = refreshTokenHash;
        this.issuedAt = issuedAt;
        this.expiresAt = expiresAt;
        this.provider = provider;
        this.providerRefreshTokenHash = providerRefreshTokenHash;
        this.revoked = revoked;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getRefreshTokenHash() {
        return refreshTokenHash;
    }

    public void setRefreshTokenHash(String refreshTokenHash) {
        this.refreshTokenHash = refreshTokenHash;
    }

    public Instant getIssuedAt() {
        return issuedAt;
    }

    public void setIssuedAt(Instant issuedAt) {
        this.issuedAt = issuedAt;
    }

    public Instant getExpiresAt() {
        return expiresAt;
    }

    public void setExpiresAt(Instant expiresAt) {
        this.expiresAt = expiresAt;
    }

    public String getProvider() {
        return provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

    public String getProviderRefreshTokenHash() {
        return providerRefreshTokenHash;
    }

    public void setProviderRefreshTokenHash(String providerRefreshTokenHash) {
        this.providerRefreshTokenHash = providerRefreshTokenHash;
    }

    public boolean isRevoked() {
        return revoked;
    }

    public void setRevoked(boolean revoked) {
        this.revoked = revoked;
    }

    @Override
    public String toString() {
        return "RefreshTokenEntity{" +
                "id=" + id +
                ", userId=" + userId +
                ", refreshTokenHash='" + refreshTokenHash + '\'' +
                ", issuedAt=" + issuedAt +
                ", expiresAt=" + expiresAt +
                ", provider='" + provider + '\'' +
                ", providerRefreshToken='" + providerRefreshTokenHash + '\'' +
                ", revoked=" + revoked +
                '}';
    }
}
